spring.application.name=admin-service
server.port=8082

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=127.0.0.1

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/IAM
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.properties.hibernate.default_schema=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Spring Cloud
spring.cloud.compatibility-verifier.enabled=false