export const clients = [
  {
    id: '1',
    initials: 'AM',
    name: 'Acme Marketing Portal',
    type: 'confidential',
    clientId: 'client_acme_mkt_001',
    redirectUris: [
      'https://app.acme.com/auth/callback',
      'https://localhost:3000/callback',
    ],
    createdAt: 'Oct 12, 2023',
  },
  {
    id: '2',
    initials: 'MP',
    name: 'Monolith Production App',
    type: 'confidential',
    clientId: 'client_mono_prod_002',
    redirectUris: [
      'https://monolith.io/callback',
    ],
    createdAt: 'Nov 04, 2023',
  },
  {
    id: '3',
    initials: 'SA',
    name: 'Support Admin Panel',
    type: 'public',
    clientId: 'client_support_003',
    redirectUris: [
      'https://support.internal/auth',
      'https://localhost:4000/callback',
    ],
    createdAt: 'Dec 19, 2023',
  },
  {
    id: '4',
    initials: 'DW',
    name: 'Data Warehouse Sync',
    type: 'machine',
    clientId: 'client_dw_sync_004',
    redirectUris: [
      'https://dw.internal/oauth/callback',
    ],
    createdAt: 'Jan 08, 2024',
  },
  {
    id: '5',
    initials: 'MB',
    name: 'Mobile Banking App',
    type: 'public',
    clientId: 'client_mobile_005',
    redirectUris: [
      'myapp://auth/callback',
    ],
    createdAt: 'Feb 14, 2024',
  },
  {
    id: '6',
    initials: 'AP',
    name: 'Analytics Pipeline',
    type: 'machine',
    clientId: 'client_analytics_006',
    redirectUris: [
      'https://analytics.internal/callback',
    ],
    createdAt: 'Mar 22, 2024',
  },
  {
    id: '7',
    initials: 'PG',
    name: 'Payment Gateway Service',
    type: 'confidential',
    clientId: 'client_payment_007',
    redirectUris: [
      'https://pay.internal/oauth/callback',
    ],
    createdAt: 'Apr 03, 2024',
  },
  {
    id: '8',
    initials: 'HR',
    name: 'HR Self-Service Portal',
    type: 'public',
    clientId: 'client_hr_portal_008',
    redirectUris: [
      'https://hr.acme.com/auth/callback',
      'https://localhost:5000/callback',
    ],
    createdAt: 'Apr 18, 2024',
  },
  {
    id: '9',
    initials: 'BI',
    name: 'BI Dashboard App',
    type: 'confidential',
    clientId: 'client_bi_dash_009',
    redirectUris: [
      'https://bi.acme.com/callback',
    ],
    createdAt: 'May 01, 2024',
  },
  {
    id: '10',
    initials: 'NT',
    name: 'Notification Service',
    type: 'machine',
    clientId: 'client_notif_010',
    redirectUris: [
      'https://notify.internal/callback',
    ],
    createdAt: 'May 15, 2024',
  },
  {
    id: '11',
    initials: 'CS',
    name: 'Customer Support Bot',
    type: 'machine',
    clientId: 'client_cs_bot_011',
    redirectUris: [
      'https://bot.support.acme.com/callback',
    ],
    createdAt: 'Jun 02, 2024',
  },
  {
    id: '12',
    initials: 'DP',
    name: 'Developer Portal',
    type: 'public',
    clientId: 'client_dev_portal_012',
    redirectUris: [
      'https://dev.acme.com/auth/callback',
      'https://localhost:8080/callback',
    ],
    createdAt: 'Jun 20, 2024',
  },
];